frontendService:
  annotations: {}
  labels: {}
  name: frontend
  ports:
  - name: tcp-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    stack: odms
    tier: frontend
  sessionAffinity: None
  sessionAffinityConfig: {}
  type: ClusterIP
