apiVersion: v1
data:
  ldif: {{ .Values.ldapSchemaConfigMap.data.LDIF | b64dec | quote}}
kind: ConfigMap
metadata:
  annotations:
{{ toYaml .Values.ldapSchemaConfigMap.annotations | indent 4 }}
  labels:
{{ toYaml .Values.ldapSchemaConfigMap.labels | indent 4 }}
  name: {{ .Values.ldapSchemaConfigMap.name }}
  namespace: {{ .Release.Namespace }}