apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.postgresSecret.data.POSTGRES_DB | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresSecret.data.POSTGRES_PASSWORD | b64enc }}
kind: Secret
metadata:
  annotations:
{{ toYaml .Values.postgresSecret.annotations | indent 4 }}
  labels:
{{ toYaml .Values.postgresSecret.labels | indent 4 }}
  name: {{ .Values.postgresSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
