apiVersion: v1
data:
  init: {{ .Values.postgresInitScriptsSecret.data.INIT }}
kind: Secret
metadata:
  annotations:
{{ toYaml .Values.postgresInitScriptsSecret.annotations | indent 4 }}
  labels:
{{ toYaml .Values.postgresInitScriptsSecret.labels | indent 4 }}
  name: {{ .Values.postgresInitScriptsSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
