apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.postgresService.annotations | indent 4 }}
  labels:
{{ toYaml .Values.postgresService.labels | indent 4 }}
  name: {{ .Values.postgresService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.postgresService.ports | indent 4 }}
  selector:
{{ toYaml .Values.postgresService.selector | indent 4 }}
  sessionAffinity: {{ .Values.postgresService.sessionAffinity }}
  sessionAffinityConfig:
{{ toYaml .Values.postgresService.sessionAffinityConfig | indent 4 }}
  type: {{ .Values.postgresService.type }}
