apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.frontendService.annotations | indent 4 }}
  labels:
{{ toYaml .Values.frontendService.labels | indent 4 }}
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.frontendService.ports | indent 4 }}
  selector:
{{ toYaml .Values.frontendService.selector | indent 4 }}
  sessionAffinity: {{ .Values.frontendService.sessionAffinity }}
  sessionAffinityConfig:
{{ toYaml .Values.frontendService.sessionAffinityConfig | indent 4 }}
  type: {{ .Values.frontendService.type }}
