apiVersion: v1
data:
  CONTEXT_DIR: {{ .Values.liquibaseDemographicsMdmConfigMap.data.CONTEXT_DIR }}
  LIQUIBASE_CHANGELOG: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_CHANGELOG }}
  LIQUIBASE_DATABASE: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_DATABASE }}
  LIQUIBASE_DEFAULT_SCHEMA_NAME: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_DEFAULT_SCHEMA_NAME }}
  LIQUIBASE_HOST: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_HOST }}
  LIQUIBASE_LOGLEVEL: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_LOGLEVEL }}
  LIQUIBASE_PASSWORD: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_PASSWORD }}
  LIQUIBASE_USERNAME: {{ .Values.liquibaseDemographicsMdmConfigMap.data.LIQUIBASE_USERNAME }}
kind: ConfigMap
metadata:
  annotations:
{{ toYaml .Values.liquibaseDemographicsMdmConfigMap.annotations | indent 4 }}
  labels:
{{ toYaml .Values.liquibaseDemographicsMdmConfigMap.labels | indent 4 }}
  name: {{ .Values.liquibaseDemographicsMdmConfigMap.name }}
  namespace: {{ .Release.Namespace }}
