apiVersion: v1
data:
  CONTEXT_DIR: {{ .Values.liquibaseMisMdmConfigMap.data.CONTEXT_DIR }}
  LIQUIBASE_CHANGELOG: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_CHANGELOG }}
  LIQUIBASE_DATABASE: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_DATABASE }}
  LIQUIBASE_DEFAULT_SCHEMA_NAME: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_DEFAULT_SCHEMA_NAME }}
  LIQUIBASE_HOST: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_HOST }}
  LIQUIBASE_LOGLEVEL: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_LOGLEVEL }}
  LIQUIBASE_PASSWORD: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_PASSWORD }}
  LIQUIBASE_USERNAME: {{ .Values.liquibaseMisMdmConfigMap.data.LIQUIBASE_USERNAME }}
kind: ConfigMap
metadata:
  annotations:
{{ toYaml .Values.liquibaseMisMdmConfigMap.annotations | indent 4 }}
  labels:
{{ toYaml .Values.liquibaseMisMdmConfigMap.labels | indent 4 }}
  name: {{ .Values.liquibaseMisMdmConfigMap.name }}
  namespace: {{ .Release.Namespace }}
