apiVersion: batch/v1
kind: Job
metadata:
  annotations:
{{ toYaml .Values.liquibaseMisMdmJob.annotations | indent 4 }}
  labels:
{{ toYaml .Values.liquibaseMisMdmJob.spec.selector.matchLabels | indent 4 }}
  name: {{ .Values.liquibaseMisMdmJob.name }}
  namespace: {{ .Release.Namespace }}
spec:
#   selector:
# {{ toYaml .Values.liquibaseMisMdmJob.spec.selector | indent 4 }}
  template:
#     metadata:
#       labels:
# {{ toYaml .Values.liquibaseMisMdmJob.spec.selector.matchLabels | indent 8 }}
    spec:
      containers:
{{ toYaml .Values.liquibaseMisMdmJob.containers | indent 8 }}
      restartPolicy: {{ .Values.liquibaseMisMdmJob.restartPolicy }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}