apiVersion: batch/v1
kind: Job
metadata:
  annotations:
{{ toYaml .Values.liquibaseEpmrJob.annotations | indent 4 }}
  labels:
{{ toYaml .Values.liquibaseEpmrJob.spec.selector.matchLabels | indent 4 }}
  name: {{ .Values.liquibaseEpmrJob.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
{{ toYaml .Values.liquibaseEpmrJob.containers | indent 8 }}
      restartPolicy: {{ .Values.liquibaseEpmrJob.restartPolicy }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}