apiVersion: v1
data:
  DB_DEMOGRAPHICS_USER: {{ .Values.backendSecret.data.DB_DEMOGRAPHICS_USER | b64enc }}
  DB_ODMS_PASSWORD: {{ .Values.backendSecret.data.DB_ODMS_PASSWORD | b64enc }}
  DB_ODMS_USER: {{ .Values.backendSecret.data.DB_ODMS_USER | b64enc }}
  DB_REGISTRIES_PASSWORD: {{ .Values.backendSecret.data.DB_REGISTRIES_PASSWORD | b64enc }}
  DB_REGISTRIES_USER: {{ .Values.backendSecret.data.DB_REGISTRIES_USER | b64enc }}
  DB_SECURITY_PASSWORD: {{ .Values.backendSecret.data.DB_SECURITY_PASSWORD | b64enc }}
  DB_SECURITY_USER: {{ .Values.backendSecret.data.DB_SECURITY_USER | b64enc }}
kind: Secret
metadata:
  annotations:
{{ toYaml .Values.backendSecret.annotations | indent 4 }}
  labels:
{{ toYaml .Values.backendSecret.labels | indent 4 }}
  name: {{ .Values.backendSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
