apiVersion: v1
kind: Service
metadata:
  annotations:
{{ toYaml .Values.backendService.annotations | indent 4 }}
  labels:
{{ toYaml .Values.backendService.labels | indent 4 }}
  name: {{ .Values.backendService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
{{ toYaml .Values.backendService.ports | indent 4 }}
  selector:
{{ toYaml .Values.backendService.selector | indent 4 }}
  sessionAffinity: {{ .Values.backendService.sessionAffinity }}
  sessionAffinityConfig:
{{ toYaml .Values.backendService.sessionAffinityConfig | indent 4 }}
  type: {{ .Values.backendService.type }}
