apiVersion: v1
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadminConfigMap.data.PGADMIN_DEFAULT_EMAIL }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadminConfigMap.data.PGADMIN_DEFAULT_PASSWORD }}
kind: ConfigMap
metadata:
  annotations:
{{ toYaml .Values.pgadminConfigMap.annotations | indent 4 }}
  labels:
{{ toYaml .Values.pgadminConfigMap.labels | indent 4 }}
  name: {{ .Values.pgadminConfigMap.name }}
  namespace: {{ .Release.Namespace }}
