liquibaseEpmrConfigMap:
  annotations: {}
  data:
    CONTEXT_DIR: /workspace/epmr
    LIQUIBASE_CHANGELOG: epmr.yaml
    LIQUIBASE_DATABASE: odms
    LIQUIBASE_DEFAULT_SCHEMA_NAME: public
    LIQUIBASE_HOST: dbms
    LIQUIBASE_LOGLEVEL: finest
    LIQUIBASE_PASSWORD: postgres
    LIQUIBASE_USERNAME: postgres
  labels: {}
  name: liquibase-epmr
