backendSecret:
  annotations: {}
  data:
    DB_DEMOGRAPHICS_USER: postgres
    DB_ODMS_PASSWORD: postgres
    DB_ODMS_USER: postgres
    DB_REGISTRIES_PASSWORD: postgres
    DB_REGISTRIES_USER: postgres
    DB_SECURITY_PASSWORD: postgres
    DB_SECURITY_USER: postgres
  labels: {}
  name: backend
